name: My First Workflow

# on:
#   push:
#   pull_request:
# jobs:
#   say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print message
#         run: echo "Hello, Github Actions!"
#       - name: Print message
#         run: echo "Making changes in PR"
#       - name: Print Names
#         run: echo "Hello , Parmeet Kaur"
#   say-bye:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print message
#         run: echo "Goodbye, Github Actions!"
#       - name: Print Names
#         run: echo "Goodbye , Parmeet Kaur"

# on: Push
# jobs:
#   run-test:
#     runs-on: ubuntu-latest
    
#     steps:
#       -run: echo "test is running"
#       -run: echo "test successful"
  
#   deploy_App:
#     needs: run_test
#     runs-on: ubuntu-latest
#     steps:
#       -run: echo "workflow successful"


on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files
        run: ls