name: My first workflow
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello, Github Actions!"
      - name: Print message
        run: echo "Parmeet Kaur"
  say-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        runs: echo " bye world"
      - name: Print message
        run: echo "Bye parmeet"